/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Nov  5 15:45:37 2016. */

#include "game.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Damage_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Damage, originatingPlayerId, originatingPlayerId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Damage, amountOfDamage, originatingPlayerId, 0),
    PB_LAST_FIELD
};

const pb_field_t GameData_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, GameData, originalPlayerId, originalPlayerId, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, GameData, damagesDone, originalPlayerId, &Damage_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(GameData, damagesDone) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Damage_GameData)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(GameData, damagesDone) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Damage_GameData)
#endif


/* @@protoc_insertion_point(eof) */
