# source files in this project (main.cpp is automatically assumed)
SOURCES := main.cpp infrared.cpp game.cpp

# header files in this project
HEADERS := infrared.hpp game.hpp

# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
